#ansible-playbook -i invfile Playbooks/vault_testing.yml -vv --ask-vault-pass
---
  - name: Run AWS Cli Commands On All Servers
    hosts: pvt
    gather_facts: yes
    become: yes
    become_user: root
    serial: 3
    vars:
     user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36343066653662346433356361653565343536663039313038363836306535396661386137313566
          3166386636653431643338626237653363346266643437330a396630313162646266623264666465
          62343931316635336333343561616363363964663966623964343334613939643164636663393734
          3536336330323262300a313631636337396637636336313165393833373030316365653564366134
          3162
    tasks:
       - name: Create .aws folder
         shell: mkdir -p /root/.aws
         ignore_errors: yes
       - name: Copy Encrypted File To /tmp
         copy:
           src: /tmp/{{item}} #This Encrypted File Must Be Created Prior To Running The Playbook.
           dest: /tmp/{{item}}
           owner: root
           group: root
           mode: '0600'
         with_items:
         - aws_creds
         - tls.key
         - tls.crt
       - name: Copy Encrypted Credentials File To .aws folder
         copy:
           src: /tmp/aws_creds #This Encrypted File Must Be Created Prior To Running The Playbook.
           dest: /root/.aws/credentials
           owner: root
           group: root
           mode: '0600'
       - name: Check S3 Buckets
         shell: aws s3 ls | cut -d " " -f 3
         register: buckets
       - name: Print Bucket Name
         debug:
          var: buckets 
       - name: Get VPCS
         shell: aws ec2 describe-vpcs | jq ".Vpcs[].VpcId" -r
         register: vpcs
       - name: Print VPC ID
         debug:
          var: vpcs        
       - name: Creating admin "{{item}}"
         user:
           name: "{{item}}"
           state: present
           comment: Admin User "{{item}}"
           groups: root
           shell: /bin/bash
           group: sudo
           password: "{{ '%s' | format(user_password) | regex_replace('\n', '') | password_hash('sha512') }}"
           password_expire_min: 1
         with_items:
         - anand
         - bala
         - chandra
         - david
       - name: Replace Password Authentication To Yes
         ansible.builtin.lineinfile:
           path: /etc/ssh/sshd_config
           regexp: '^PasswordAuthentication no'
           line: PasswordAuthentication yes
           backup: yes
         notify:
         -  Restart SSH Service
    handlers:
      - name: Restart SSH Service
        shell: service sshd restart