---
  - name: Play for Install Nginx on WebServers
    hosts: pvt
    gather_facts: yes
    become: yes
    become_user: root
    vars:
      mysql_socket: /var/lib/mysql/mysql.sock
      mysql_port: 3306
      mysql_data_dir: /var/lib/mysql
      mysql_pid_file: /var/lib/mysql/mysqld.pid
      mysql_slow_query_log_enabled: true
      mysql_slow_query_log: 1
      mysql_slow_query_log_file: /var/lib/mysql/mysql-slow.log
      mysql_long_query_time: 3
      mysql_slow_query_time: 3
      mysql_innodb_buffer_pool_size: 5734M
      mysql_innodb_log_file_size: 1433M
      mysql_max_connections: 682
      mysql_thread_cache_size: 102
      mysql_binding_address: "0.0.0.0"
      hostname: "{{ inventory_hostname }}"
    tasks:
       - name: Copy the index.j2 Template to index destination folder.
         template: >
            src=/root/ansiblecode/Playbooks/4.Jinja/mysql_conf.j2
            dest=/tmp/my.cnf
            owner=root
            group=root
            mode=0644