---
  - name: Play for Install Nginx on WebServers
    hosts: pvt:!testserver01
    gather_facts: yes
    become: yes
    become_user: root
    #serial: 1 #Executes the playbook one host at a time.
    tasks:
       - name: Run Apt Update
         shell: apt update
         tags:
           - update

       - name: Clone Git Repo
         shell: cd /tmp && git clone -b DevSecOpsB36 --single-branch https://github.com/mavrick202/dockertest1.git
         tags:
           - clone

       - name: Install Nginx Server
         apt: >  # > symbol Will consider as a single line.
           name=nginx
           state=present
         tags:
           - install

       - name: Copy the files to index destination folder.
         copy: > # > symbol Will consider as a single line.
            src=/tmp/dockertest1/index.html
            dest=/var/www/html/index.nginx-debian.html
            remote_src=yes
            owner=root
            group=root
            mode=0644
         ignore_errors: yes #Will Proceed to next task even it failed.
         tags:
           - index

       - name: Copy the style files to  destination folder.
         copy: >
            src=/tmp/dockertest1/style.css
            dest=/var/www/html/style.css
            remote_src=yes
            owner=root
            group=root
            mode=0644
         tags:
           - style

       - name: Copy the javascript files to  destination folder.
         copy: >
            src=/tmp/dockertest1/scorekeeper.js
            dest=/var/www/html/scorekeeper.js
            remote_src=yes
            owner=root
            group=root
            mode=0644
         tags:
           - js

       - name: restart nginx
         command: service nginx restart
         tags:
          - restart

       - name: Delete Git Repo
         shell: rm -rf /tmp/dockertest1
         tags:
          - delete