---
- name: Play For Installing Nginx On WebServers
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Copy html file
    copy:
      src: "{{ item }}"
      dest: /var/www/html/{{ item }}
      owner: root
      group: root
      mode: '0644'
    with_items:
    - contact.html
    - orders.html
    - aboutus.html